#### general settings
name: DeFlow-NTIRE-RWSR
use_tb_logger: true
model: SRFL_Glow
distortion: sr
scale: 4
gpu_ids: [0,] # should be equal to $CUDA_VISIBLE_DEVICES


#### datasets
datasets:
  train:
    name: NTIRE-RWSR
    mode: LQGT_multiclass 
    dataroot_GT: [../datasets/NTIRE-RWSR/Corrupted-tr-y/4x/, 
                  ../datasets/NTIRE-RWSR/Corrupted-tr-x/1x/]
    dataroot_LQ: [../datasets/NTIRE-RWSR/Corrupted-tr-y/16x/,
                  ../datasets/NTIRE-RWSR/Corrupted-tr-x/4x/]
    quant: 32
    n_workers: 3  # per GPU
    batch_size: 8
    GT_size: 160
    balanced: true
    preload: False # set true to load images into ram for faster training
    use_shuffle: true
    use_flip: true
    use_crop: true
    color: RGB

  val:
    name: NTIRE-RWSR
    mode: LQGT_multiclass 
    dataroot_GT: [../datasets/NTIRE-RWSR/track1-valid-gt/4x/, 
                  ../datasets/NTIRE-RWSR/Corrupted-va-x/1x/]
    dataroot_LQ: [../datasets/NTIRE-RWSR/track1-valid-gt/16x/, 
                  ../datasets/NTIRE-RWSR/Corrupted-va-x/4x/]
    preload: False # set true to load images into ram for faster training
    center_crop_hr_size: 160
    quant: 32
    n_max: 100

#### network structure
network_G:
  which_model_G: RRDBGlowNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
  upscale: 4
  train_RRDB: true
  # train_RRDB_delay: 0.5

  flow:
    K: 16
    L: 3
    noInitialInj: true
    LU_decomposed: true
    coupling: CondAffineSeparatedAndCond
    additionalFlowNoAffine: 2
    split:
      enable: true
    fea_up0: true
    stackRRDB:
      blocks: [1, 8, 15, 22]
      concat: true
    shift:
      constant: correlated
      classes: [[0,1], ]
      std_init_shift: 0.0
    LR_noise_std: 0.03
    CondAffineSeparatedAndCond:
      eps: 0.001
      multReverse: True

#### path
path:
  root: /srv/beegfs02/scratch/data_aim2019/data/STValentin/ 
  pretrain_model_G: /srv/beegfs02/scratch/data_aim2019/data/STValentin/models/RRDB_PSNR_x4.pth #/srv/beegfs02/scratch/data_aim2019/data/STValentin/models/SrgDf2kRRDB23X4Qn32_K16_L3_sp_CondAffineSeparatedAndCond_FlowNoAff2_n200000_fullDSNoRot_lr25e-5s05s075s09s095_RrdbD05_RRDBStack4_latest_G.pth #
  strict_load: true
  resume_state: auto

#### training settings: learning rate scheme, loss
train:
  manual_seed: 10
  lr_G: !!float 0.5e-4
  weight_decay_G: 0
  beta1: 0.9
  beta2: 0.99
  lr_scheme: MultiStepLR
  warmup_iter: -1  # no warm up
  lr_steps_rel: [0.5, 0.75, 0.9, 0.95]
  lr_gamma: 0.5

  niter: 100000
  val_freq: 20000

#### validation settings
val:
  heats: [1.0]
  n_sample: 1

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
